# Generated by Django 4.2.2 on 2023-06-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0002_added_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_manager.translation'),
        ),
    ]
