# Generated by Django 4.2.2 on 2023-06-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0003_change_one_to_one_to_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='synopis',
            field=models.TextField(blank=True, verbose_name='Synopis of the series.'),
        ),
    ]
