# Generated by Django 4.2.2 on 2023-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0004_add_synopis_to_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name of the genre')),
                ('description', models.TextField(verbose_name='description of the genre')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='translation_manager.genre'),
        ),
    ]
