# Generated by Django 4.2.2 on 2023-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0006_add_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published Date and Time'),
        ),
    ]
